# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Fake CD: Build app WITHOUT code signing"
  lane :build_only do
    build_app(
      workspace: "CINewsCD.xcworkspace",
      scheme: "CINewsCD",
      configuration: "Release",
      skip_archive: true,
      xcargs: "CODE_SIGNING_ALLOWED=NO"
    )
  end
end

